name: Test unitarios por clase

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Dar permisos de ejecución a Gradle Wrapper
      run: chmod +x gradlew

    - name: Compilar con Gradle
      run: ./gradlew build
